"""add sm2 fields

Revision ID: 821937dd1346
Revises: 2f88b0b3019a
Create Date: 2025-12-03 14:42:12.388376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '821937dd1346'
down_revision: Union[str, Sequence[str], None] = '2f88b0b3019a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_word_progress', sa.Column('easiness_factor', sa.Float(), nullable=True))
    op.add_column('user_word_progress', sa.Column('interval', sa.Integer(), nullable=True))
    op.add_column('user_word_progress', sa.Column('repetitions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_word_progress', 'repetitions')
    op.drop_column('user_word_progress', 'interval')
    op.drop_column('user_word_progress', 'easiness_factor')
    # ### end Alembic commands ###
